spring.application.name=LoginPUC
spring.profiles.active=dev

app.user.username=leo
app.user.password=4321
app.admin.username=admin
app.admin.password=1234

# H2 Database
spring.datasource.url=jdbc:h2:file:./data/loginpuc
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# API SendEmail
spring.mail.host=smtp.gmail.com  
spring.mail.port=587
spring.mail.username=seu_email@gmail.com
# https://myaccount.google.com/apppasswords
# sua senha de app aqui
spring.mail.password=senhadeapp  
spring.mail.properties.mail.smtp.auth=true  
spring.mail.properties.mail.smtp.starttls.enable=true 