spring.application.name=RadioBrowserAPI
spring.profiles.active=dev
radio.search.api.base.url=https://de1.api.radio-browser.info/json/stations/search
supabase.url=https://SEU-PROJETO.supabase.co/rest/v1/favorites
supabase.service-key=troque-por-placeholder