spring.application.name=SecureLoginPuc_v2

# =========================================================
# USUÁRIO
# =========================================================

app.user.username=user
app.user.password=4321
app.user.name=Usuario


# =========================================================
# ADMINISTRADOR
# =========================================================

app.admin.username=admin
app.admin.password=1234
app.admin.name=Administrador


# =========================================================
# GMAIL
# =========================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


# =========================================================
# GOOGLE reCAPTCHA
# =========================================================

recaptcha.site-key=${RECAPTCHA_SITE_KEY}
recaptcha.secret-key=${RECAPTCHA_SECRET_KEY}